### This script was generated by chatgpt to test the ECB/CBC oracle

import socket
import struct
import os

HOST = "127.0.0.1"
PORT = 1337

def recv_exact(sock: socket.socket, n: int) -> bytes:
    """Receive exactly n bytes or raise ConnectionError."""
    chunks = []
    got = 0
    while got < n:
        chunk = sock.recv(n - got)
        if not chunk:
            raise ConnectionError("Socket closed while receiving data")
        chunks.append(chunk)
        got += len(chunk)
    return b"".join(chunks)

def recv_until(sock: socket.socket, marker: bytes, max_bytes: int = 65536) -> bytes:
    """Receive until marker appears (included), or raise if too big."""
    data = bytearray()
    while marker not in data:
        chunk = sock.recv(4096)
        if not chunk:
            raise ConnectionError("Socket closed while waiting for prompt")
        data += chunk
        if len(data) > max_bytes:
            raise RuntimeError("Prompt too large / marker not found")
    return bytes(data)

def main():
    # Example plaintext (you can change this)
    plaintext = b"A" * 64  # nice for ECB/CBC detection tests

    # Choose a guess randomly just to test the roundtrip
    guess = b"1" if (os.urandom(1)[0] & 1) else b"0"  # ASCII '0' or '1'

    with socket.create_connection((HOST, PORT), timeout=5) as s:
        # Send length-prefixed plaintext
        s.sendall(struct.pack("!I", len(plaintext)))
        s.sendall(plaintext)

        # Receive length-prefixed ciphertext
        m = struct.unpack("!I", recv_exact(s, 4))[0]
        ct = recv_exact(s, m)

        print(f"Received ciphertext length: {m}")
        print(f"Ciphertext (hex, first 64 bytes): {ct[:64].hex()}")

        # Receive the prompt text (server sends it after ciphertext)
        prompt = recv_until(s, b"> ")
        print("\n--- Server prompt ---")
        print(prompt.decode("utf-8", errors="replace"), end="")

        # Send guess ('0' for CBC, '1' for ECB)
        s.sendall(guess)
        print(guess.decode(), "(sent)")

        # Read server response:
        # If your server sends text like "Correct!/Wrong!", read remaining data.
        # If your server sends a single byte result (0/1), read exactly 1.
        s.settimeout(1.0)
        try:
            resp = s.recv(4096)
            if resp:
                # Heuristic: if it's printable, show as text; else show as byte value
                if all(32 <= b <= 126 or b in (10, 13, 9) for b in resp):
                    print("\n--- Server response (text) ---")
                    print(resp.decode("utf-8", errors="replace"))
                else:
                    print("\n--- Server response (binary) ---")
                    print(f"Result byte: {resp[0]} (1=correct, 0=wrong)")
            else:
                print("\nServer closed without extra response.")
        except socket.timeout:
            print("\nNo extra response (timeout).")

if __name__ == "__main__":
    main()
